# --- Created by Slick DDL
# To stop Slick DDL generation, remove this comment and start using Evolutions

# --- !Ups

create table "projects" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"name" VARCHAR NOT NULL,"owner" INTEGER NOT NULL);
create table "rights" ("project" INTEGER NOT NULL,"user" INTEGER NOT NULL,"read" BOOLEAN NOT NULL,"write" BOOLEAN NOT NULL);
alter table "rights" add constraint "pk_right" primary key("project","user");
create table "users" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"name" VARCHAR NOT NULL,"email" VARCHAR NOT NULL,"password" VARCHAR NOT NULL);
alter table "projects" add constraint "fk_project_user" foreign key("owner") references "users"("id") on update NO ACTION on delete NO ACTION;
alter table "rights" add constraint "fk_right_project" foreign key("project") references "projects"("id") on update NO ACTION on delete NO ACTION;
alter table "rights" add constraint "fk_right_user" foreign key("user") references "users"("id") on update NO ACTION on delete NO ACTION;

# --- !Downs

alter table "projects" drop constraint "fk_project_user";
alter table "rights" drop constraint "fk_right_project";
alter table "rights" drop constraint "fk_right_user";
drop table "projects";
alter table "rights" drop constraint "pk_right";
drop table "rights";
drop table "users";

