package clide.reactive.ui.schema

import org.scalajs.dom._

trait HTML {
  def a()          = document.createElement("a").asInstanceOf[HTMLAnchorElement]
  def abbr()       = document.createElement("abbr").asInstanceOf[HTMLElement]
  @deprecated("Not supported in HTML5. Use <abbr> instead", "HTML 5")
  def acronym()    = document.createElement("acronym").asInstanceOf[HTMLElement]
  def address()    = document.createElement("address").asInstanceOf[HTMLElement]
  @deprecated("Not supported in HTML5. Use <object> instead", "HTML 5")
  def applet()     = document.createElement("applet").asInstanceOf[HTMLAppletElement] 
  def area()       = document.createElement("area").asInstanceOf[HTMLAreaElement]
  def aside()      = document.createElement("aside").asInstanceOf[HTMLElement]
  def audio()      = document.createElement("audio").asInstanceOf[HTMLAudioElement]
  def b()          = document.createElement("b").asInstanceOf[HTMLElement]
  def base()       = document.createElement("base").asInstanceOf[HTMLBaseElement]
  @deprecated("Not supported in HTML5. Use CSS instead", "HTML 5")
  def basefont()   = document.createElement("basefont").asInstanceOf[HTMLElement] 
  def bdi()        = document.createElement("bdi").asInstanceOf[HTMLElement]
  def bdo()        = document.createElement("bdo").asInstanceOf[HTMLElement]
  @deprecated("Not supported in HTML5. Use CSS instead", "HTML 5")
  def big()        = document.createElement("big").asInstanceOf[HTMLElement]
  def blockquote() = document.createElement("blockquote").asInstanceOf[HTMLQuoteElement]
  def body()       = document.createElement("body").asInstanceOf[HTMLBodyElement]
  def br()         = document.createElement("br").asInstanceOf[HTMLBRElement]
  def button()     = document.createElement("button").asInstanceOf[HTMLButtonElement]
  def canvas()     = document.createElement("canvas").asInstanceOf[HTMLCanvasElement]
  def caption()    = document.createElement("caption").asInstanceOf[HTMLTableCaptionElement]
  @deprecated("Not supported in HTML5. Use CSS instead", "HTML 5")
  def center()     = document.createElement("center").asInstanceOf[HTMLTableCaptionElement]  
  def cite()       = document.createElement("cite").asInstanceOf[HTMLElement]
  def code()       = document.createElement("code").asInstanceOf[HTMLElement]
  def col()        = document.createElement("col").asInstanceOf[HTMLTableColElement]
  def colgroup()   = document.createElement("colgroup").asInstanceOf[HTMLElement]
  def command()    = document.createElement("command").asInstanceOf[HTMLElement]
  def datalist()   = document.createElement("datalist").asInstanceOf[HTMLDataListElement]
  def dd()         = document.createElement("dd").asInstanceOf[HTMLDDElement]
  def del()        = document.createElement("del").asInstanceOf[HTMLElement]
  def details()    = document.createElement("details").asInstanceOf[HTMLElement]
  def dfn()        = document.createElement("dfn").asInstanceOf[HTMLElement]
  def dialog()     = document.createElement("dialog").asInstanceOf[HTMLElement]
  @deprecated("Not supported in HTML5. Use <ul> instead", "HTML 5") 
  def dir()        = document.createElement("dir").asInstanceOf[HTMLElement]
  def div()        = document.createElement("div").asInstanceOf[HTMLDivElement]   
  def dl()         = document.createElement("dl").asInstanceOf[HTMLDListElement]
  def dt()         = document.createElement("dt").asInstanceOf[HTMLDTElement]
  def em()         = document.createElement("em").asInstanceOf[HTMLElement]
  def embed()      = document.createElement("embed").asInstanceOf[HTMLEmbedElement]
  def fieldset()   = document.createElement("fieldset").asInstanceOf[HTMLFieldSetElement]
  def figcaption() = document.createElement("figcaption").asInstanceOf[HTMLElement]
  def figure()     = document.createElement("figure").asInstanceOf[HTMLElement]
  @deprecated("Not supported in HTML5. Use CSS instead", "HTML 5")
  def font()       = document.createElement("font").asInstanceOf[HTMLFormElement]
  def footer()     = document.createElement("footer").asInstanceOf[HTMLElement]
  def form()       = document.createElement("form").asInstanceOf[HTMLFormElement]
  @deprecated("Not supported in HTML5.", "HTML 5")
  def frame()      = document.createElement("frame").asInstanceOf[HTMLElement]
  @deprecated("Not supported in HTML5.", "HTML 5")
  def frameset()   = document.createElement("frameset").asInstanceOf[HTMLFormElement]
  def h1()         = document.createElement("h1").asInstanceOf[HTMLHeadingElement]
  def h2()         = document.createElement("h2").asInstanceOf[HTMLHeadingElement]
  def h3()         = document.createElement("h3").asInstanceOf[HTMLHeadingElement]
  def h4()         = document.createElement("h4").asInstanceOf[HTMLHeadingElement]
  def h5()         = document.createElement("h5").asInstanceOf[HTMLHeadingElement]
  def h6()         = document.createElement("h6").asInstanceOf[HTMLHeadingElement]
  def head()       = document.createElement("head").asInstanceOf[HTMLHeadElement]
  def header()     = document.createElement("header").asInstanceOf[HTMLElement]
  def hr()         = document.createElement("hr").asInstanceOf[HTMLHRElement]
  def html()       = document.createElement("html").asInstanceOf[HTMLElement]
  def i()          = document.createElement("i").asInstanceOf[HTMLElement]
  def iframe()     = document.createElement("iframe").asInstanceOf[HTMLIFrameElement]
  def img(src: String, alt: String) = {
    val elem = document.createElement("img").asInstanceOf[HTMLImageElement]
    elem.src = src
    elem.alt = alt
    elem
  }
  def input()      = document.createElement("input").asInstanceOf[HTMLInputElement]
  def ins()        = document.createElement("ins").asInstanceOf[HTMLElement]
  def kbd()        = document.createElement("kbd").asInstanceOf[HTMLElement]
  def keygen()     = document.createElement("keygen").asInstanceOf[HTMLElement]
  def label()      = document.createElement("label").asInstanceOf[HTMLLabelElement]
  def legend()     = document.createElement("legend").asInstanceOf[HTMLLegendElement]
  def li()         = document.createElement("li").asInstanceOf[HTMLLIElement]
  def link()       = document.createElement("link").asInstanceOf[HTMLLinkElement]
  def main()       = document.createElement("main").asInstanceOf[HTMLElement]
  def map()        = document.createElement("map").asInstanceOf[HTMLMapElement]
  def mark()       = document.createElement("mark").asInstanceOf[HTMLElement]
  def math()       = document.createElement("math").asInstanceOf[HTMLElement]
  def menu()       = document.createElement("menu").asInstanceOf[HTMLMenuElement]
  def meta()       = document.createElement("meta").asInstanceOf[HTMLMetaElement]
  def meter()      = document.createElement("meter").asInstanceOf[HTMLElement]
  def nav()        = document.createElement("nav").asInstanceOf[HTMLElement]
  @deprecated("Not supported in HTML5.", "HTML 5")
  def noframes()   = document.createElement("noframes").asInstanceOf[HTMLElement]
  def `object`()   = document.createElement("object").asInstanceOf[HTMLObjectElement]
  def ol()         = document.createElement("ol").asInstanceOf[HTMLOListElement]
  def optgroupt()  = document.createElement("optgroupt").asInstanceOf[HTMLOptGroupElement]
  def option()     = document.createElement("option").asInstanceOf[HTMLOptionElement]
  def output()     = document.createElement("output").asInstanceOf[HTMLElement]
  def p()          = document.createElement("p").asInstanceOf[HTMLParagraphElement]
  def param()      = document.createElement("param").asInstanceOf[HTMLParamElement]
  def pre()        = document.createElement("pre").asInstanceOf[HTMLPreElement]
  def progress()   = document.createElement("progress").asInstanceOf[HTMLProgressElement]
  def q()          = document.createElement("q").asInstanceOf[HTMLQuoteElement]
  def rp()         = document.createElement("rp").asInstanceOf[HTMLElement]
  def rt()         = document.createElement("rt").asInstanceOf[HTMLElement]
  def ruby()       = document.createElement("ruby").asInstanceOf[HTMLElement]
  def s()          = document.createElement("s").asInstanceOf[HTMLElement]
  def samp()       = document.createElement("samp").asInstanceOf[HTMLElement]
  def script()     = document.createElement("script").asInstanceOf[HTMLScriptElement]
  def section()    = document.createElement("section").asInstanceOf[HTMLElement]
  def select()     = document.createElement("select").asInstanceOf[HTMLSelectElement]
  def small()      = document.createElement("small").asInstanceOf[HTMLElement]
  def source()     = document.createElement("source").asInstanceOf[HTMLSourceElement]
  def span()       = document.createElement("span").asInstanceOf[HTMLSpanElement]
  @deprecated("Not supported in HTML5. Use <del> instead", "HTML 5")  
  def strike()     = document.createElement("strike").asInstanceOf[HTMLElement]
  def strong()     = document.createElement("strong").asInstanceOf[HTMLElement]
  def style()      = document.createElement("style").asInstanceOf[HTMLStyleElement]
  def sub()        = document.createElement("sub").asInstanceOf[HTMLElement]
  def summary()    = document.createElement("summary").asInstanceOf[HTMLElement]
  def sup()        = document.createElement("sup").asInstanceOf[HTMLElement]
  def svg()        = document.createElement("svg").asInstanceOf[HTMLElement]
  def table()      = document.createElement("table").asInstanceOf[HTMLTableElement]
  def tbody()      = document.createElement("tbody").asInstanceOf[HTMLTableSectionElement]
  def td()         = document.createElement("td").asInstanceOf[HTMLTableCellElement]
  def textarea()   = document.createElement("textarea").asInstanceOf[HTMLTextAreaElement]
  def tfoot()      = document.createElement("tfoot").asInstanceOf[HTMLTableSectionElement]
  def th()         = document.createElement("th").asInstanceOf[HTMLTableHeaderCellElement]
  def thead()      = document.createElement("thead").asInstanceOf[HTMLTableSectionElement]
  def time()       = document.createElement("time").asInstanceOf[HTMLElement]
  def title()      = document.createElement("title").asInstanceOf[HTMLTitleElement]
  def tr()         = document.createElement("tr").asInstanceOf[HTMLTableRowElement]
  def track()      = document.createElement("track").asInstanceOf[HTMLTrackElement]
  @deprecated("Not supported in HTML5. Use CSS instead", "HTML 5")
  def tt()         = document.createElement("tt").asInstanceOf[HTMLTableRowElement]
  def u()          = document.createElement("u").asInstanceOf[HTMLElement]
  def ul()         = document.createElement("ul").asInstanceOf[HTMLUListElement]
  def `var`()      = document.createElement("var").asInstanceOf[HTMLElement]
  def video()      = document.createElement("video").asInstanceOf[HTMLVideoElement]
  def wbr()        = document.createElement("wbr").asInstanceOf[HTMLElement]
}